### ISSUE TITLE
Could not process file random error

### ISSUE THREAD

**Issue by aufr33** [enzo1982/superfast#3] opened 2020-12-09 09:18 UTC
I encountered a serious bug in freaccmd when using the superopus codec. The problem is that the error "Could not process file" appears randomly. I don't know what it depends on, it happens completely by accident.

For testing, I used a 48000 Hz 16 bit Stereo wav file. Audio length and content don't matter.

Freaccmd version: v1.1 Alpha 20180716
OS: Windows 10 Pro

Here's a sample output:

> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> Processing file: test3.wav...done.
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> Processing file: test3.wav...done.
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> Processing file: test3.wav...done.
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> **Could not process file:** test3.wav
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> Processing file: test3.wav...done.
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> **Could not process file:** test3.wav
>  
> C:\AUDIO\test>C:\soft\freac-mt\freaccmd.exe -e superopus -o "test3.opus" test3.wav
> Processing file: test3.wav...done.

The problem only occurs with the superopus codec. When using the usual opus codec, everything is ok, but I really need superopus, since it uses multithreading.

**Comment by enzo1982** [comment] 2020-12-09 16:43
Please don't use this code anymore. The SuperFast codecs have been integrated into mainline fre:ac and lot's of bugs have been fixed in the meantime.

With fre:ac 1.1.3, the syntax to use the Opus codec in SuperFast mode is: `freaccmd -e opus --superfast -o out.opus in.wav`

While trying this, I found a minor issue with freaccmd. When converting .wav files, freaccmd will use the FFmpeg decoder extension instead of the usual libsndfile. Conversion will still work of course, but you will see a lot of FFmpeg output on the console. I'll check to see what's causing this and will fix it in the next release.

**Comment by enzo1982** [comment] 2020-12-09 23:51
So, I actually checked if I could reproduce the issue you're seeing with fre:ac 1.1.3. And yes, it's still there. This issue is caused by a race condition when checking whether the file has been enqueued for processing already.

It's now fixed in the fre:ac repository. If you need a fixed version now, let me know and I'll build one.

I also already fixed the issue with FFmpeg being used as the decoder for .wav files, by the way.

**Comment by aufr33** [comment] 2020-12-10 01:16
Thank you so much! You can of course release a fixed version.

**Comment by enzo1982** [comment] 2020-12-10 23:02
Alright, you can download a fixed version for Windows at [freac.org/updates/freac-1.1.3-20201210-windows-x64.zip](https://freac.org/updates/freac-1.1.3-20201210-windows-x64.zip).

Let me know if this fixes the issues.

**Comment by aufr33** [comment] 2020-12-11 07:27
This version is really stable. I ran it many times and never got any errors.

**Closed as completed** 2020-12-11 08:16 UTC

**Comment by enzo1982** [comment] 2020-12-11 10:13
Great! Thanks for reporting back!

I'll archive this repository now. Please post any further issues in [enzo1982/freac](/enzo1982/freac) or [enzo1982/BoCA](/enzo1982/BoCA).
